from jnpr.junos import Device
from jnpr.junos.utils.config import Config

with Device(host='30.0.0.54', user='root', passwd='Juniper') as dev:
	with Config(dev) as cu:
		cu.load("set interfaces em0 unit 0 family inet address 13.0.0.2/24", format="set")
		cu.load("set interfaces em1 unit 0 family inet address 19.0.0.1/24", format="set")
		cu.load("set interfaces em2 unit 0 family inet address 192.168.2.1/24", format="set")
		cu.load("set interfaces lo0 unit 0 family inet address 5.5.5.5/32", format="set")
		cu.load("set protocols ospf area 0 interface em0.0", format="set")
		cu.load("set protocols ospf area 0 interface em1.0", format="set")
		cu.load("set protocols ospf area 0 interface lo0.0", format="set")
		cu.load("set protocols ospf traffic-engineering", format="set")
		cu.load("set routing-options autonomous-system 100", format="set")
		cu.load("set protocols bgp group AS100-300 type external", format="set")
		cu.load("set protocols bgp group AS100-300 peer-as 300", format="set")
		cu.load("set protocols bgp group AS100-300 neighbor 192.168.2.2 peer-as 300", format="set")
		cu.load("set protocols bgp group INTERNAL type internal", format="set")	
		cu.load("set protocols bgp group INTERNAL peer-as 100", format="set")	
		cu.load("set protocols bgp group INTERNAL neighbor 1.1.1.1 peer-as 100", format="set")
		cu.load("set protocols bgp group INTERNAL local-address 5.5.5.5", format="set")
		cu.load("set protocols bgp group INTERNAL export exportar_ruta_de_192.168.2.2", format="set")
		cu.load("set interfaces em0 unit 0 family mpls", format="set")
		cu.load("set interfaces em1 unit 0 family mpls", format="set")
		cu.load("set interfaces lo0 unit 0 family mpls", format="set")
		cu.load("set protocols mpls interface em0.0", format="set")
		cu.load("set protocols mpls interface em1.0", format="set")
		cu.load("set protocols mpls interface lo0.0", format="set")
		cu.load("set protocols rsvp interface em0.0", format="set")
		cu.load("set protocols rsvp interface em1.0", format="set")
		cu.load("set protocols rsvp interface lo0.0", format="set")
		cu.load("set protocols mpls label-switched-path R-5_TO_R-1 to 1.1.1.1", format="set")	
		cu.load("set policy-options policy-statement exportar_ruta_de_192.168.2.2 term 1 from neighbor 192.168.2.2", format="set")
		cu.load("set policy-options policy-statement exportar_ruta_de_192.168.2.2 term 1 then accept", format="set")
		cu.load("set system host-name R-5", format="set")
		cu.pdiff()
		cu.commit()
		print("Configuración de la interfaz aplicada con éxito.")	
